### ISSUE TITLE
Command: Theme generation

### ISSUE THREAD

**Issue by bitpshr** [dojo/cli#168] opened 2017-10-20 16:57 UTC
**Enhancement**

We should create a tool that helps with theme generation. Specifically, the tool should help improve the following processes:

* Scaffolding necessary files
* Validating classes (either at build time or run time)
* Including theme in application build

Package Version: rc

**Comment by umaar** [comment] 2017-11-22 17:56
Still learning, so some ideas might not make sense!

# Exploring ideas to improve the theming story

# Introduction

This GitHub comment outlines my investigation into the mechanisms and potential improvements for theming.

The points below are numbered so you can quickly refer to it in your response.

# 1. Clarification on one problem we wish to solve

When theming some widgets, for example [built-in Dojo 2 Button widget](https://github.com/dojo/widgets/tree/master/src/button), you may wish to override the existing [styling](https://github.com/dojo/widgets/blob/aa66ea65909874c01132386de9560d10233ca7fd/src/button/styles/button.m.css#L3-L6):

Note: A widget must specify class names as themable so they be overridden.

When you, an end-user, would like to consume a widget and override its themable classes, you might create a new CSS file `styles/themes/dark/button.m.css`:

```css
.selector1 {
  color: red;
}

.selector2 {
  color: blue;
}
```

The main problem is this: How does an end user know: a) which selectors they can style. b) What part of the widget is affected by such a selector.

# 2. Potential solution: Autosuggest

As a user, if I were writing a theme CSS file for a widget, it'd be great to get autosuggest values for the available selectors. Some editors do this based on the HTML which is detected.

__How__: I can only think of users having to install a custom code editor plugin which isn't ideal. So this is probably not feasible.

# 3. Potential solution: Scaffolding

Just like how there are [tools](http://extractcss.com/) and [plugins](https://atom.io/packages/html-to-css) to convert HTML to CSS, what if we could generate a `styles/themes/dark/button.m.css` file automatically, with the selectors already present, and rules ready to be filled in?

__How__:

* A new command part of the Dojo CLI which inspects + evaluates the widget source to determine their themable classes
* Extract information/hints from readme/code comments which a widget author must add to their widget source code, this can be picked up via the CLI and used to generate a CSS file

__To think about__:

* This could be a large engineering effort with lots of delicate pieces
* Would the scaffold command work on an existing CSS file? E.g. if the user had already started writing one?
* What happens when a widget is updated, will the scaffold tool handle the new classes correctly?

# 4. Potential solution: Terminal logging

What if the Dojo CLI logged a message to the terminal to alert the user when they have used a class which is not themeable.

__To think about__:

* We haven't solved the problem of telling the user which classes were available from the start
* Extra noise to already noisy CLI output

# 5. Potential solution: DevTools console logging

What if the browser console logged the available themable classes.

__To think about__:

* Could be easier to compute this client side, rather than having to do source code inspection like with solution 4
* Messages can be disabled in production
* Messages can be grouped using the Console API to decrease the noise
* When dealing with styling related concerns, the user is likely to have browser DevTools already open
* Not all users will be running the Dojo CLI/have DevTools open when developing their app, in an ideal world, the user has the information they need as they're writing the CSS file
* Inspecting a class in the DOM Tree doesn't tell you whether it is themable

# 6. Potential solution: Education

Educate and encourage widget authors to add all themable classes to their readme documentation.

__To think about__:

* This has a maintenance cost: widget authors must always remember to keep documentation up to date
* Smaller engineering effort than some other options

# 7. Potential solution: DevTools extension

Inspect and see original class names through a DevTools extension.

__To think about__:

* Is not ideal to ask the user to install additional tools
* Extra engineering effort to develop + maintain browser extensions
* What browsers to support?
* Whenever I think about needing an extension to do accomplish something relatively small in a similar context, I wonder if there is a deeper problem with the approach which was taken

# 8. Potential solution: Removing the unique classname transformation

In a traditional app, if I were using a third party component, I might inspect it with DevTools, see what classes are used, write out the class in my `custom.css` file and override things. Dojo 2 users can't do that because the classes have been "scoped" and can change. What if Dojo 2 was rearchitected so original class names were preserved? This would help with the problem being discussed in this comment, but also have improved developer ergonomics in view-source, inspect-element & testing workflows. To achieve the goal of scoping CSS, that could be explored separately (for example something like the [scoped](https://css-tricks.com/saving-the-day-with-scoped-css/) attribute - however this was removed from the spec).

To clarify: if we achieve this, the user would then have to 'inspect element' and use the class in their theme, however this doesn't necessarily identify which classes are available for theming and which are not.

__To think about__:

* Large engineering effort
* Can improve the experience of debugging Dojo 2 apps


# A side issue

When exploring themes, I tried to understand how I could extend an existing theme from `node_modules`.

The problem is this: If you try to use `composes` with compiled/built CSS code:

```
composes: root from '../../../../node_modules/@dojo/widgets/themes/dojo/button.m.css';
```

The classes in that file have been 'scoped' and cannot be imported as the user would expect.

# 9. Potential solution: Publish raw CSS

Publish the raw CSS files (e.g. to the NPM repository) so they can be 'composed' from directly,

__To think about__:

- For the the user, it's an additional/potentially unintutive step, e.g. it might be unclear what file they need to compose from
- External widget authors need to be aware of this step, but also must set up the infrastructure to do it

# 10. Potential solution: Extend the composes method

Noticed that the raw CSS module turns into a few files, one of which is: `node_modules/@dojo/widgets/themes/dojo/button.m.css.js` which has a piece of JSON inside it like this:

```
{"root":"_1lZxc2Ul","addon":"TAlDrfED","pressed":"_37ji2mWW","popup":"_29G5UqBS","disabled":"GlYj4g4z"," _key":"dojo-button"}
```

So I wonder if the `composes` function (not sure who or what implements it) can somehow be enhanced so if it detects a .js extension:

```
.selector {
  composes: root from '../../../../node_modules/@dojo/widgets/themes/dojo/button.m.js' /* <-- Notice the .js extension */
}
```

It automatically reads the JSON from that file and figures out which style rule you meant.

# 11. Potential solution: Extend the composes method with source maps

When you write ` composes: root from '../../../../node_modules/@dojo/widgets/themes/dojo/button.m.css';`

The `composes` function could check if there is a sourcemap, if there is, it extracts the relevant (e.g. `root`) selector from the original file since the source map should have this information.

# Another side issue:

Would be nice to enhance the `composes` function so it provides logging if it can not find the class the user is trying to import.

**Comment by umaar** [comment] 2017-11-23 09:05
@agubler @matt-gadd @kitsonk let me know if you have any thoughts/clarifications 👍

**Comment by tomdye** [comment] 2017-11-27 15:54
Having spent some time looking into this, I think that the problem of scaffolding out a new theme for existing widgets can be achieved by making a few changes to our theming approach:

* Move theme and fixed css classes into separate css files within widgets. 
* Move all themable `css` to top level `theme` directory
* Change the ` _key` created within `grunt-dojo2` to use the `packagename` from `package.json`. For example the `Button` key from our `widgets` repo would change from `dojo-button` to `@dojo/widgets/button`.

The above changes create a structure which allows for themeable css to be easily located and for it's location to be consistent between both distributable components and a users application.

I have created a command line POC that locates and scaffolds a theme for a user given the packagenames they with to theme and the widgets within those packages. This uses the generate `.m.css.d.ts` files.

Links:
* [New theme structure](https://github.com/tomdye/dojoThemeStructure)
* [Command line POC](https://github.com/tomdye/themeScaffoldPoc)

POC Video:
![choice 1](https://user-images.githubusercontent.com/814453/33275635-3314445e-d38b-11e7-9218-6e178a0b1712.gif)

**Comment by umaar** [comment] 2018-01-02 14:08
This comment is concerning project coordination to enable the theme generation command. This comment is mainly for my benefit. As there are a few 'moving pieces', I really want to make sure my understanding on this is solid, hence the long explanation! There's nothing critical people need to read.

This comment is full of assumptions on my part so I hope people can correct any mistakes you notice! This is my understanding of what we need to do to accomplish this goal:

To run: `dojo create app -n my-app` and then `dojo create theme` and successfully create a theme file and CSS files.

When the user runs: `dojo create app`, the repo `dojo/cli-create-app` is used to scaffold out a new app. The package.json of that repo, comes from here: `src/templates/package.json` so we need to consider two things here:

1. Is the reference to `"@dojo/widgets": "~0.3.0"` up to date? Will it pull in the latest version of `dojo/widgets`?
2. When you run `dojo create something` in your brand new Dojo 2 app, it checks for a repo in `node_modules` named `cli-create-something`. We have created a `https://github.com/dojo/cli-create-theme` (PR still needs merging) so we need to add that repo to the `devDependencies` of the templated `package.json` within  `cli-create-app`. (question: can we merge it?)

The above two points, when executed, should mean: when you run `dojo create app -n my-app`, you now get a new command `dojo create theme`.

Moving onto the next point: the widgets repo has changed, and as a result, its 'output' (e.g. the artifact) must also change. This will not happen by default. To clarify what the change is: The artifact is a `dojo-widgets-0.3.1-rc.1.tgz` file. Unzipping that presents a file like `dojo-widgets/dist/package/theme/button/button.m.css.js` which contains a snippet of code like this: `" _key":"dojo-button"`. Our goal was to change that so it turns into: `" _key":"@dojo/widgets/button"`

To achieve this: We must ensure `dojo/widgets` pulls in the latest `grunt-dojo2` which (I think) it already does as `"grunt-dojo2": "latest"` is present in the `package.json` file of the `dojo/widgets` repo. When it pulls in the latest `grunt-dojo2` code (warning: PR still needs to be merged), it will receive new functionality which means means building the widgets repo will in turn create `dojo-widgets/dist/package/theme/button/button.m.css.js` files which has this: `" _key":"@dojo/widgets/button"`

Finally, when we run `dojo create theme`, thanks to the points previously mentioned, it should work!

**Comment by umaar** [comment] 2018-01-02 14:20
Also can we merge this one? https://github.com/dojo/cli-create-theme/pull/1

**Comment by umaar** [comment] 2018-01-02 15:04
We have discussed part of https://github.com/dojo/cli/issues/168#issuecomment-354773648 and agreed that when scaffolding out a new app, we will _not_ bundle this new `create theme` command with it.

Would still appreciate a review on https://github.com/dojo/cli-create-theme/pull/1 !

**Comment by umaar** [comment] 2018-01-03 11:11
Can we start 'releasing' projects? More so that I and others can test the feature out end-to-end and we could do some QA on it! Do we have any resources that explain the whole process? Like when do we release and how does it work, and who does it?

**Comment by agubler** [comment] 2018-02-11 20:07
I think we can consider this epic as closed now that we have published the initial release of `@dojo/cli-create-theme` - All enhancements are now tracked as issues on the cli-create-theme repo.

**Closed by agubler** 2018-02-11 20:07 UTC
Labels: blocker, enhancement
